### ISSUE TITLE
Improve project description

### ISSUE THREAD

**Issue by BabyFnord** [SteffMUC/openDTU_wDisplay2#2]
Hi there,

some may find themselves lost when starting from scratch with OpenDTU + OLED display on a breakout board, as learning about and/or choosing a suitable setup or profile is tricky, due to the many hardware variants out there. I had a bumpy start because I did not order a 38-pin ESP32 module at first (PCBs were still being produced at the time I ordered the required parts, I did not have KiCad at that time), and I only found out about uploading [nodemcu_esp32.json](https://github.com/tbnobody/OpenDTU/blob/master/docs/DeviceProfiles/nodemcu_esp32.json) as `Pin Mapping` by trial and error. Hence my suggestion to include the required ESP32 module type _and_ a link to the required device profile in the project description.

At least I would suggest that including those notes help in getting folks jump on this project.

Thanks for sharing! 🙌

**Comment by SteffMUC** [comment]
Fixed in https://github.com/SteffMUC/openDTU_wDisplay2/commit/ca8b40e09506fc29c84bab7fd1e2ed9f67b026da

**Comment by SteffMUC** [comment]
Improved readme with extension of this information:
Configuration file [nodemcu_esp32.json](https://github.com/tbnobody/OpenDTU/blob/master/docs/DeviceProfiles/nodemcu_esp32.json) available in [openDTU](https://github.com/tbnobody/OpenDTU), please select "Generic NodeMCU 32 with SSD1306" as profile
In case you struggle how to configure [openDTU](https://github.com/tbnobody/OpenDTU), the documentation can be found here [openDTU Display documentation](https://github.com/tbnobody/OpenDTU/blob/master/docs/Display.md)
The PCB is designed to work with ESP32S NodeMCU (38 Pins) e.g. [Amazon](https://www.amazon.de/gp/product/B0BF5NRF8H/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&th=1)
